In [8]:
import numpy as np

In [23]:
a = np.arange(6).reshape(1,-1) + 10

In [24]:
a

array([[10, 11, 12, 13, 14, 15]])

In [21]:
np.argmax(a)

5

In [27]:
np.argmax(a, axis=1)

array([5])

In [14]:
a = np.arange(6) + 10

In [15]:
a

array([10, 11, 12, 13, 14, 15])

In [18]:
np.argmax(a)

5