In [1]:
import os, sys
sys.path.append('lib')
import numpy as np
from kmeans import kMeans_init_centroids, run_kMeans, find_closest_centroids
from InputDataProcessor import InputDataProcessor 

In [2]:
idp=InputDataProcessor(bucket_name='aiml_harveen', use_case='c3w1/kmeans', file_name='ex7_X.npy')

In [3]:
X=idp.loadNumpy()

c3w1/kmeans/orig_data/ex7_X.npy


In [4]:
X=X[:5]

In [5]:
X

array([[1.84207953, 4.6075716 ],
       [5.65858312, 4.79996405],
       [6.35257892, 3.2908545 ],
       [2.90401653, 4.61220411],
       [3.23197916, 4.93989405]])

In [6]:
K = 3
max_iters = 10

In [7]:
initial_centroids = kMeans_init_centroids(X, K)

In [8]:
initial_centroids

array([[6.35257892, 3.2908545 ],
       [1.84207953, 4.6075716 ],
       [3.23197916, 4.93989405]])

In [9]:
find_closest_centroids(X,initial_centroids)

array([1, 0, 0, 2, 2])

In [10]:
centroids, idx = run_kMeans(X, initial_centroids, max_iters)

K-Means iteration 0/9
K-Means iteration 1/9
K-Means iteration 2/9
K-Means iteration 3/9
K-Means iteration 4/9
K-Means iteration 5/9
K-Means iteration 6/9
K-Means iteration 7/9
K-Means iteration 8/9
K-Means iteration 9/9


In [11]:
centroids

array([[6.00558102, 4.04540928],
       [1.84207953, 4.6075716 ],
       [3.06799784, 4.77604908]])

In [12]:
K = 3
max_iters = 20

In [13]:
initial_centroids = kMeans_init_centroids(X, K)

In [14]:
centroids, idx = run_kMeans(X, initial_centroids, max_iters)

K-Means iteration 0/19
K-Means iteration 1/19
K-Means iteration 2/19
K-Means iteration 3/19
K-Means iteration 4/19
K-Means iteration 5/19
K-Means iteration 6/19
K-Means iteration 7/19
K-Means iteration 8/19
K-Means iteration 9/19
K-Means iteration 10/19
K-Means iteration 11/19
K-Means iteration 12/19
K-Means iteration 13/19
K-Means iteration 14/19
K-Means iteration 15/19
K-Means iteration 16/19
K-Means iteration 17/19
K-Means iteration 18/19
K-Means iteration 19/19


In [15]:
centroids

array([[1.84207953, 4.6075716 ],
       [6.00558102, 4.04540928],
       [3.06799784, 4.77604908]])

In [16]:
K = 3
max_iters = 50

In [17]:
initial_centroids = kMeans_init_centroids(X, K)

In [18]:
centroids, idx = run_kMeans(X, initial_centroids, max_iters)

K-Means iteration 0/49
K-Means iteration 1/49
K-Means iteration 2/49
K-Means iteration 3/49
K-Means iteration 4/49
K-Means iteration 5/49
K-Means iteration 6/49
K-Means iteration 7/49
K-Means iteration 8/49
K-Means iteration 9/49
K-Means iteration 10/49
K-Means iteration 11/49
K-Means iteration 12/49
K-Means iteration 13/49
K-Means iteration 14/49
K-Means iteration 15/49
K-Means iteration 16/49
K-Means iteration 17/49
K-Means iteration 18/49
K-Means iteration 19/49
K-Means iteration 20/49
K-Means iteration 21/49
K-Means iteration 22/49
K-Means iteration 23/49
K-Means iteration 24/49
K-Means iteration 25/49
K-Means iteration 26/49
K-Means iteration 27/49
K-Means iteration 28/49
K-Means iteration 29/49
K-Means iteration 30/49
K-Means iteration 31/49
K-Means iteration 32/49
K-Means iteration 33/49
K-Means iteration 34/49
K-Means iteration 35/49
K-Means iteration 36/49
K-Means iteration 37/49
K-Means iteration 38/49
K-Means iteration 39/49
K-Means iteration 40/49
K-Means iteration 41/49
K-

In [19]:
centroids

array([[5.65858312, 4.79996405],
       [2.6593584 , 4.71988992],
       [6.35257892, 3.2908545 ]])

In [20]:
K = 3
max_iters = 100

In [21]:
initial_centroids = kMeans_init_centroids(X, K)

In [22]:
centroids, idx = run_kMeans(X, initial_centroids, max_iters)

K-Means iteration 0/99
K-Means iteration 1/99
K-Means iteration 2/99
K-Means iteration 3/99
K-Means iteration 4/99
K-Means iteration 5/99
K-Means iteration 6/99
K-Means iteration 7/99
K-Means iteration 8/99
K-Means iteration 9/99
K-Means iteration 10/99
K-Means iteration 11/99
K-Means iteration 12/99
K-Means iteration 13/99
K-Means iteration 14/99
K-Means iteration 15/99
K-Means iteration 16/99
K-Means iteration 17/99
K-Means iteration 18/99
K-Means iteration 19/99
K-Means iteration 20/99
K-Means iteration 21/99
K-Means iteration 22/99
K-Means iteration 23/99
K-Means iteration 24/99
K-Means iteration 25/99
K-Means iteration 26/99
K-Means iteration 27/99
K-Means iteration 28/99
K-Means iteration 29/99
K-Means iteration 30/99
K-Means iteration 31/99
K-Means iteration 32/99
K-Means iteration 33/99
K-Means iteration 34/99
K-Means iteration 35/99
K-Means iteration 36/99
K-Means iteration 37/99
K-Means iteration 38/99
K-Means iteration 39/99
K-Means iteration 40/99
K-Means iteration 41/99
K-

In [29]:
centroids

array([[1.95399466, 5.02557006],
       [3.04367119, 1.01541041],
       [6.03366736, 3.00052511]])

In [31]:
K = 3
max_iters = 500
initial_centroids = kMeans_init_centroids(X, K)
centroids, idx = run_kMeans(X, initial_centroids, max_iters)
centroids

K-Means iteration 0/499
K-Means iteration 1/499
K-Means iteration 2/499
K-Means iteration 3/499
K-Means iteration 4/499
K-Means iteration 5/499
K-Means iteration 6/499
K-Means iteration 7/499
K-Means iteration 8/499
K-Means iteration 9/499
K-Means iteration 10/499
K-Means iteration 11/499
K-Means iteration 12/499
K-Means iteration 13/499
K-Means iteration 14/499
K-Means iteration 15/499
K-Means iteration 16/499
K-Means iteration 17/499
K-Means iteration 18/499
K-Means iteration 19/499
K-Means iteration 20/499
K-Means iteration 21/499
K-Means iteration 22/499
K-Means iteration 23/499
K-Means iteration 24/499
K-Means iteration 25/499
K-Means iteration 26/499
K-Means iteration 27/499
K-Means iteration 28/499
K-Means iteration 29/499
K-Means iteration 30/499
K-Means iteration 31/499
K-Means iteration 32/499
K-Means iteration 33/499
K-Means iteration 34/499
K-Means iteration 35/499
K-Means iteration 36/499
K-Means iteration 37/499
K-Means iteration 38/499
K-Means iteration 39/499
K-Means it

array([[3.04367119, 1.01541041],
       [1.95399466, 5.02557006],
       [6.03366736, 3.00052511]])

In [ ]:
array([[1.95399466, 5.02557006],
       [3.04367119, 1.01541041],
       [6.03366736, 3.00052511]])

In [40]:
K = 3
max_iters =500
initial_centroids = kMeans_init_centroids(X, K)
centroids, idx = run_kMeans(X, initial_centroids, max_iters)
centroids

K-Means iteration 0/499
K-Means iteration 1/499
K-Means iteration 2/499
K-Means iteration 3/499
K-Means iteration 4/499
K-Means iteration 5/499
K-Means iteration 6/499
K-Means iteration 7/499
K-Means iteration 8/499
K-Means iteration 9/499
K-Means iteration 10/499
K-Means iteration 11/499
K-Means iteration 12/499
K-Means iteration 13/499
K-Means iteration 14/499
K-Means iteration 15/499
K-Means iteration 16/499
K-Means iteration 17/499
K-Means iteration 18/499
K-Means iteration 19/499
K-Means iteration 20/499
K-Means iteration 21/499
K-Means iteration 22/499
K-Means iteration 23/499
K-Means iteration 24/499
K-Means iteration 25/499
K-Means iteration 26/499
K-Means iteration 27/499
K-Means iteration 28/499
K-Means iteration 29/499
K-Means iteration 30/499
K-Means iteration 31/499
K-Means iteration 32/499
K-Means iteration 33/499
K-Means iteration 34/499
K-Means iteration 35/499
K-Means iteration 36/499
K-Means iteration 37/499
K-Means iteration 38/499
K-Means iteration 39/499
K-Means it

array([[3.04367119, 1.01541041],
       [6.03366736, 3.00052511],
       [1.95399466, 5.02557006]])

In [ ]:
array([[3.04367119, 1.01541041],
       [1.95399466, 5.02557006],
       [6.03366736, 3.00052511]])